export type JobInput = {
  localJobId?: number;
  title: string;
  department: string;
  jobDescription: string;
  responsibilities: string;
  requiredSkills: string;
  preferredSkills: string;
  minimumExperience: number;
  salary: number | null;
  currency: string;
  minSalary: number | null;
  maxSalary: number | null;
  payFrequency: "YEARLY" | "MONTHLY" | "HOURLY" | "";
  location: string;
  workplaceType: "ON_SITE" | "HYBRID" | "REMOTE";
  employmentType: "FULL_TIME" | "PART_TIME" | "CONTRACT" | "TEMPORARY" | "OTHER" | "VOLUNTEER" | "INTERNSHIP";
  seniorityLevel: string;
  openingsCount: number;
  closingDate: string;
  sourceFileName?: string;
  sourceFileType?: string;
  applyUrl?: string;
  jobBoards: string[];
  linkedinJobTitleId: string;
  linkedinCompanyId: string;
  linkedinLocationId: string;
  notificationEmail: string;
};

export type Candidate = {
  job_candidate_id: number;
  job_posting_id: number;
  external_application_id: string | null;
  full_name: string | null;
  email_address: string | null;
  phone_number: string | null;
  headline: string | null;
  candidate_location: string | null;
  linkedin_profile_url: string | null;
  resume_url: string | null;
  current_company: string | null;
  current_position: string | null;
  years_of_experience: number | null;
  application_status: string | null;
  match_score: number | null;
  matching_skills: string | null;
  missing_skills: string | null;
  relevant_experience: string | null;
  match_strengths: string | null;
  match_concerns: string | null;
  match_summary: string | null;
  applied_at: string | null;
  job_title: string | null;
};

export type JobOption = { job_posting_id: number; title: string | null; posting_status: string | null };

export type JobListItem = {
  job_posting_id: number;
  external_job_id: string | null;
  apply_url?: string | null;
  job_boards?: string | null;
  title: string | null;
  department: string | null;
  location: string | null;
  workplace_type: string | null;
  employment_type: string | null;
  salary?: number | null;
  currency?: string | null;
  min_salary?: number | null;
  max_salary?: number | null;
  pay_frequency?: string | null;
  openings_count: number | null;
  posting_status: string | null;
  applicant_count: number;
  created_at: string | null;
  published_at: string | null;
  closing_date: string | null;
};
